feat(calculate-shipping): option to cubage avoidingmax dimensions in multiple quantity
ecomplus/app-correios-v2 pull request #14
Opened 2023-11-09 03:46 UTC by matheusgnreis

2023-11-09 03:47 UTC, matheusgnreis commented
Carrinhos com muitos produtos está estourando o limite dos correios, no caso a ideia ai é considerar sempre a maior dimensao e somar os pesos.

2023-11-09 18:25 UTC, leomp12 requested changes
Do jeito que c fez aqui vai ficar trocando altura por largura por comprimento 🙃

2023-11-09 18:31 UTC, leomp12 commented on functions/routes/ecom/modules/calculate-shipping.js
>              for (let i = 0; i < quantity; i++) {
Aliás se não estiver somando dimensões nem faz sentido entrar nesse loop

2023-11-09 18:31 UTC, leomp12 commented on functions/ecom.config.js
> +        "description": "Ao selecionado, será considerado a maior dimensão e somado os pesos"
```suggestion
    "use_bigger_box": {
      "schema": {
        "type": "boolean",
        "default": false,
        "title": "Calcular considerando apenas uma caixa",
        "description": "Se selecionado as dimensões não serão somadas, considerando o maior valor de cada dimensão entre os itens"
```

_greater_ tem outro sentido, tipo _mais legal_ ou _melhor_ 😄 
_maior_ no sentido literal é _bigger_ mesmo...

2023-11-09 18:33 UTC, leomp12 commented
> Carrinhos com muitos produtos está estourando o limite dos correios

Esse limite é global? Se for faz sentido deixar mockado no código mesmo, resetando pra baixo quando passar, assim como acontece com os mínimos

2023-11-09 20:10 UTC, matheusgnreis commented
> > Carrinhos com muitos produtos está estourando o limite dos correios
> 
> Esse limite é global? Se for faz sentido deixar mockado no código mesmo, resetando pra baixo quando passar, assim como acontece com os mínimos

Isso, a soma das 3 dimensoes não pode dar maior que 200

2023-11-09 21:53 UTC, leomp12 commented on functions/routes/ecom/modules/calculate-shipping.js
> +            }
Isso aqui não tá fazendo muito sentido também não, porque você checa os máximos ainda no loop, antes mesmo de acabar de calcular as dimensões?
E não dá pra jogar de 100 pra 15 arbitrariamente, por exemplo, se 100 é o máximo você deveria manter em 100 se passar disso, e se o máximo somado é 200 você deveria resetar as 3 dimensões pro máximo possível de cada se a soma passar de 200. Isso fora dos loops, ao final do cálculo das dimensões, acho até que deveria estar em `functions/lib/correios-calculate.js` na verdade

2023-11-10 15:02 UTC, matheusgnreis commented on functions/routes/ecom/modules/calculate-shipping.js
> +            }
Pronto.

2023-11-10 15:53 UTC, leomp12 commented on functions/lib/correios-calculate.js
> +      }
Isso aqui não corrige a dimensão usada no cálculo

2023-11-10 15:58 UTC, leomp12 commented on functions/routes/ecom/modules/calculate-shipping.js
>                  pkgDimension.value = dimensionValue
Você tinha que estar checando o `side` aqui tambem

2023-11-10 16:17 UTC, leomp12 commented
https://github.com/ecomplus/app-correios-v2/commit/5e2bf48c53a850b80b3434bf928f0a5c2ab63edd

2023-11-10 16:17 UTC, closed without merging